orbs:
  gcp-cli: circleci/gcp-cli@1.8.4
version: 2.1
jobs:
  install_gcloud_CLI:
    description: |
      Install gcloud CLI and initialize to connect to Google Cloud
    executor: <<parameters.executor>>
    parameters:
      executor:
        default: neux_circleci
        description: |
          Executor to use for this job. Defaults to this orb's default executor.
        type: executor
      gcloud-service-key:
        default: 01a67ada57f20374bbd49f8eceb6e2d51ac07c91
        description: The gcloud service key
        type: env_var_name
      google-project-id:
        default: screenshot-demo-0317-project
        description: The Google project ID to connect with via the gcloud CLI
        type: env_var_name
    steps:
      - install
      - initialize:
          gcloud-service-key: <<parameters.gcloud-service-key>>
          google-compute-zone: <<parameters.google-compute-zone>>
          google-project-id: <<parameters.google-project-id>>
  build:
    docker:
      - image: circleci/node:10.16.3-browsers
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      # Download and cache dependencies
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}

      - run:
          name: install-npm-wee
          command: npm install

      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules

      # - run:
      #     name: run storybook
      #     command: npm run storybook
      #     background: true

      # - run:
      #     name: take shots
      #     command: npm run storycap

      - run:
          name: run regreesion
          command: npm run regression


